from .text import TextPortletForm
from .average_rating import AverageRatingForm
from .cart import CartPortletForm
from .categories import CategoriesPortletForm
from .delivery_time import DeliveryTimeForm
from .filter import FilterPortletForm
from .forsale import ForsaleForm
from .latest import LatestForm
from .pages import PagesForm
from .recent_products import RecentProductsForm
from .related_products import RelatedProductsForm
from .topseller import TopsellerForm